# Generated by Django 4.1.3 on 2022-11-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tittle',
            new_name='title',
        ),
    ]
