# Generated by Django 4.1.3 on 2022-11-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0002_rename_tittle_listing_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='numbers_of_bathrooms',
            new_name='num_bathrooms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='numbers_of_bedrooms',
            new_name='num_bedrooms',
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
